import * as fs from 'fs';
import * as path from 'path';
import cac from 'cac';

// This file extracts fields from package.json and generates src/package.ts
// Usage: ts-node scripts/extract-package-fields.ts <fieldName1> <fieldName2> ...

const cli = cac('extract-package-fields');

cli
    .usage('<fieldName1> <fieldName2> ...')
    .help()
    .example('ts-node scripts/extract-package-fields.ts name version author')
    .option('--output <path>', 'Output file path', {
        default: path.resolve(__dirname, '../src/package.ts'),
    });

cli
    .command('[fields...]', 'Extract fields from package.json')
    .action(
        (fields: string[], options: { output: string; }) => {
            if (!fields || fields.length === 0) {
                showHelp();
                process.exit(1);
            }

            const packageJsonPath = path.resolve(__dirname, '../package.json');
            const outputPath = options.output;
            const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));

            const notice = `// This file is generated by extract-package-fields.ts. Do not edit manually.\n\n`;
            let output = notice;
            let missingFields: string[] = [];

            for (const fieldName of fields) {
                const fieldValue = packageJson[fieldName];
                if (fieldValue === undefined) {
                    missingFields.push(fieldName);
                    continue;
                }
                output += `export const ${fieldName} = ${JSON.stringify(fieldValue, null, 2)};\n`;
            }

            fs.writeFileSync(outputPath, output);

            if (missingFields.length > 0) {
                console.warn(`Warning: The following fields were not found in package.json: ${missingFields.join(', ')}`);
            }
            console.log(`Fields extracted and saved to ${outputPath}.`);
        }
    );

function showHelp() {
    console.log(`\nUsage: ts-node scripts/extract-package-fields.ts <fieldName1> <fieldName2> ...`);
    console.log(`Example: ts-node scripts/extract-package-fields.ts name version author`);
    console.log(`\nOptions:`);
    console.log(`  --output <path>   Output file path (default: src/package.ts)`);
}

cli.parse();
