// This file extracts fields from package.json and generates src/package.ts
// Usage: ts-node scripts/extract-package-field.ts <fieldName1> <fieldName2> ...

import * as fs from 'fs';
import * as path from 'path';

const extractNames = process.argv.slice(2);
if (extractNames.length === 0) {
    console.error('Please provide at least one field name as a CLI argument.');
    process.exit(1);
}

const packageJsonPath = path.resolve(__dirname, '../package.json');
const outputPath = path.resolve(__dirname, '../src/package.ts');

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));

const notice = `// This file is generated by extract-package-field.ts. Do not edit manually.\n`;
let output = notice;
let missingFields: string[] = [];

for (const extractName of extractNames) {
    const fieldValue = packageJson[extractName];

    if (fieldValue === undefined) {
        missingFields.push(extractName);
        continue;
    }
    
    output += `export const ${extractName} = ${JSON.stringify(fieldValue, null, 2)};\n`;
}

fs.writeFileSync(outputPath, output);

if (missingFields.length > 0) {
    console.warn(`Warning: The following fields were not found in package.json: ${missingFields.join(', ')}`);
}
console.log(`Fields extracted and saved to src/package.ts.`);
