// This file is generated by extract-package-fields.ts. Do not edit manually.

export const name = "work-weeks";
export const version = "1.25.3";
export const author = "Max Zakharzhevskiy <maxzz@msn.com>";
