// This file is generated by extract-package-field.ts. Do not edit manually.
export const name = "work-weeks";
export const version = "1.25.1";
export const author = "Max Zakharzhevskiy <maxzz@msn.com>";
